/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example


import kotlinx.cli.*

fun main(args: Array<String>) {
    val parser = ArgParser("cli-sample")
    val name by parser.option(ArgType.String, shortName = "n", description = "ユーザー名").required()
    val verbose by parser.option(ArgType.Boolean, shortName = "v", description = "詳細モード")

    parser.parse(args)
    println("こんにちは, $name")
    if (verbose == true) {
        println("詳細モードが有効です")
    }
}
